parameters:
  - name: projectName
    type: string

  - name: envVarScript
    type: object
    default:
      customScript: ""
      awsSSMParamPathList: ""
      awsRegion: ""
      dotEnvFileDir: ./dotEnvFile
      dotEnvFileName: .env
      dotEnvFileStoreName: ""
      dotEnvFileArtifactName: dotEnvFile

  - name: build
    type: object
    default:
      projectType: ""
      tfChildDir: .
      dkrFile: Dockerfile
      dkrImageRepoName: ""
      dkrImageTag: latest
      artifactName: ""
      artifactDir: .

  - name: test
    type: object
    default:
      - testType: unit
        environmentName: local
        script: |
          echo "unit tests in the local environment"

      - testType: int
        environmentName: local
        script: |
          echo "integration tests in the local environment"

      - testType: int
        environmentName: qa
        script: |
          echo "integration tests in the qa environment"

  - name: deploy
    type: object
    default:
      - environmentName: test
        projectType: ""
        tfChildDir: .
        dist: .

      - environmentName: qa
        projectType: ""
        tfChildDir: .
        dist: .

stages:
  - template: ./stages/build.yml
    parameters:
      projectName: ${{ parameters.projectName }}
      projectType: ${{ parameters.build.projectType }}

      customScript: ${{ parameters.envVarScript.customScript }}
      awsSSMParamPathList: ${{ parameters.envVarScript.awsSSMParamPathList }}
      awsRegion: ${{ parameters.envVarScript.awsRegion }}
      dotEnvFileDir: ${{ parameters.envVarScript.dotEnvFileDir }}
      dotEnvFileName: ${{ parameters.envVarScript.dotEnvFileName }}
      dotEnvFileStoreName: ${{ parameters.envVarScript.dotEnvFileStoreName }}
      dotEnvFileArtifactName: ${{ parameters.envVarScript.dotEnvFileArtifactName }}

      tfChildDir: ${{ parameters.build.tfChildDir }}

      dkrFile: ${{ parameters.build.dkrFile }}
      dkrImageRepoName: ${{ parameters.build.dkrImageRepoName }}
      dkrImageTag: ${{ parameters.build.dkrImageTag }}

      artifactName: ${{ parameters.build.artifactName }}
      artifactDir: ${{ parameters.build.artifactDir }}

  - ${{ each item in parameters.test }}:
      - template: ./stages/test.yml
        parameters:
          projectName: ${{ parameters.projectName }}
          testType: ${{ item.testType }}
          environmentName: ${{ item.environmentName }}
          script: ${{ item.script }}

          dependsOnStage:
            - build
            - ${{ if eq(item.environmentName, 'qa') }}:
                - deploy_qa

          customScript: ${{ parameters.envVarScript.customScript }}
          awsSSMParamPathList: ${{ parameters.envVarScript.awsSSMParamPathList }}
          awsRegion: ${{ parameters.envVarScript.awsRegion }}
          dotEnvFileDir: ${{ parameters.envVarScript.dotEnvFileDir }}
          dotEnvFileName: ${{ parameters.envVarScript.dotEnvFileName }}
          dotEnvFileStoreName: ${{ parameters.envVarScript.dotEnvFileStoreName }}
          dotEnvFileArtifactName: ${{ parameters.envVarScript.dotEnvFileArtifactName }}

  - ${{ each item in parameters.deploy }}:
      - template: ./stages/deploy.yml
        parameters:
          projectName: ${{ parameters.projectName }}
          projectType: ${{ item.projectType }}

          dependsOnStage:
            - build
            - ${{ if gt(length(parameters.test), 0) }}:
                - test_local_unit
                - test_local_int
                - ${{ if eq(item.environmentName, 'prod') }}:
                    - test_qa_int

          environmentName: ${{ item.environmentName }}
          artifactName: ${{ parameters.build.artifactName }}
          tfChildDir: ${{ item.tfChildDir }}
          dkrImageRepoName: ${{ item.dkrImageRepoName }}
          dkrImageTag: ${{ item.dkrImageTag }}
          dist: ${{ item.dist }}

          customScript: ${{ parameters.envVarScript.customScript }}
          awsSSMParamPathList: ${{ parameters.envVarScript.awsSSMParamPathList }}
          awsRegion: ${{ parameters.envVarScript.awsRegion }}
          dotEnvFileDir: ${{ parameters.envVarScript.dotEnvFileDir }}
          dotEnvFileName: ${{ parameters.envVarScript.dotEnvFileName }}
          dotEnvFileStoreName: ${{ parameters.envVarScript.dotEnvFileStoreName }}
          dotEnvFileArtifactName: ${{ parameters.envVarScript.dotEnvFileArtifactName }}
