parameters:
  - name: projectName
    type: string
  - name: projectType
    type: string

  # for parameter see: ../stages/load-variables.yml
  - name: envVarScript
    type: object

  # for parameter see: ../stages/build.yml
  - name: build
    type: object

  # for parameter see: ../stages/test.yml
  #
  # supported tests: unit, int
  - name: test
    type: object
    default: []

  # for parameter see: ../stages/deploy.yml
  #
  # supported environments: qa, prod
  - name: deploy
    type: object
    default: []

stages:
  - ${{ if or(eq(parameters.projectName, ''), eq(parameters.projectType, '')) }}:
      - stage: no_action
        jobs:
          - job: no_action
            steps:
              - step: no_action
                script: |
                  echo 'pipeline not implemented.'
                  exit 1

  - ${{ else }}:
      - template: ../stages/build.yml
        parameters:
          projectName: ${{ parameters.projectName }}
          projectType: ${{ parameters.projectType }}

          customScript: ${{ parameters.envVarScript.customScript }}
          awsSSMParamPathList: ${{ parameters.envVarScript.awsSSMParamPathList }}
          awsRegion: ${{ parameters.envVarScript.awsRegion }}
          dotEnvFileDir: ${{ parameters.envVarScript.dotEnvFileDir }}
          dotEnvFileName: ${{ parameters.envVarScript.dotEnvFileName }}
          dotEnvFileStoreName: ${{ parameters.envVarScript.dotEnvFileStoreName }}
          dotEnvFileArtifactName: ${{ parameters.envVarScript.dotEnvFileArtifactName }}

          tfChildDir: ${{ parameters.build.tfChildDir }}

          dkrFile: ${{ parameters.build.dkrFile }}
          dkrImageRepoName: ${{ parameters.build.dkrImageRepoName }}
          dkrImageTag: ${{ parameters.build.dkrImageTag }}

          artifactName: ${{ parameters.build.artifactName }}
          artifactDir: ${{ parameters.build.artifactDir }}

      - ${{ each item in parameters.test }}:
          - template: ../stages/test.yml
            parameters:
              projectName: ${{ parameters.projectName }}
              testType: ${{ item.testType }}
              environmentName: ${{ item.environmentName }}
              script: ${{ item.script }}

              dependsOnStage:
                - build
                - ${{ if eq(item.environmentName, 'qa') }}:
                    - deploy_qa

              customScript: ${{ parameters.envVarScript.customScript }}
              awsSSMParamPathList: ${{ parameters.envVarScript.awsSSMParamPathList }}
              awsRegion: ${{ parameters.envVarScript.awsRegion }}
              dotEnvFileDir: ${{ parameters.envVarScript.dotEnvFileDir }}
              dotEnvFileName: ${{ parameters.envVarScript.dotEnvFileName }}
              dotEnvFileStoreName: ${{ parameters.envVarScript.dotEnvFileStoreName }}
              dotEnvFileArtifactName: ${{ parameters.envVarScript.dotEnvFileArtifactName }}

      - ${{ each item in parameters.deploy }}:
          - template: ../stages/deploy.yml
            parameters:
              projectName: ${{ parameters.projectName }}
              projectType: ${{ parameters.projectType }}

              dependsOnStage:
                - build
                - test_local_unit
                - test_local_int
                - ${{ if eq(item.environmentName, 'prod') }}:
                    - test_qa_int

              environmentName: ${{ item.environmentName }}
              artifactName: ${{ item.artifactName }}
              tfChildDir: ${{ item.tfChildDir }}
              dkrImageRepoName: ${{ item.dkrImageRepoName }}
              dkrImageTag: ${{ item.dkrImageTag }}
              dist: ${{ item.dist }}

              customScript: ${{ parameters.envVarScript.customScript }}
              awsSSMParamPathList: ${{ parameters.envVarScript.awsSSMParamPathList }}
              awsRegion: ${{ parameters.envVarScript.awsRegion }}
              dotEnvFileDir: ${{ parameters.envVarScript.dotEnvFileDir }}
              dotEnvFileName: ${{ parameters.envVarScript.dotEnvFileName }}
              dotEnvFileStoreName: ${{ parameters.envVarScript.dotEnvFileStoreName }}
              dotEnvFileArtifactName: ${{ parameters.envVarScript.dotEnvFileArtifactName }}
