parameters:
  ###################################################################
  #                                                                 #
  #   global parameters                                             #
  #                                                                 #
  ###################################################################
  - name: projectType # required. Must be one of: cloud, container, web
    type: string
    values:
      - cloud
      - container
      - web

  - name: dotEnvFileArtifactName # required if "projectType" = "web"
    type: string
    default: ""

  - name: dotEnvFileArtifactPath # required if "projectType" = "web"
    type: string
    default: ""

  ###################################################################
  #                                                                 #
  #   build-cloud.yml parameters                                    #
  #                                                                 #
  ###################################################################
  # optional if "projectType" = "cloud".
  # Leave empty if root directory, e.g. '.'
  # Terraform execution directory.
  # Name of directory to pass to `-chdir`, e.g. $(Build.SourcesDirectory)/module
  - name: tfChildDir
    type: string
    default: .

  ###################################################################
  #                                                                 #
  #   build-container.yml parameters                                #
  #                                                                 #
  ###################################################################
  - name: dkrFile # optional if "projectType" = "container". Default = Dockerfile
    type: string
    default: Dockerfile

  - name: dkrECRUrl # required if "projectType" = "container".
    type: string
    default: ""

  - name: dkrTag # optional if "projectType" = "container". Default = latest
    type: string
    default: latest # ${{ parameters.dkrECRUrl }}/${{ parameters.dkrRegistryName }}:${{ parameters.dkrImageTag }}

  ###################################################################
  #                                                                 #
  #   post-build.yml parameters                                     #
  #                                                                 #
  ###################################################################
  - name: artifactName # optional, leave blank if you do not need artifacts
    type: string
    default: ""

  - name: artifactDir # Default = '.' e.g. $(Build.SourcesDirectory)/dist
    type: string
    default: "."

jobs:
  - job: build
    displayName: build ${{ parameters.projectType }}
    steps:
      - ${{ if eq(parameters.projectType, 'web') }}:
          - template: ../steps/artifact-download.yml
            parameters:
              # required - force AZ Pipelines validator to throw an error
              ${{ if ne(parameters.dotEnvFileArtifactName, '') }}:
                artifactName: ${{ parameters.dotEnvFileArtifactName }}

          - template: ../steps/build-web.yml
            parameters:
              # required - force AZ Pipelines validator to throw an error
              ${{ if ne(parameters.dotEnvFileArtifactPath, '') }}:
                dotEnvFilePath: ${{ parameters.dotEnvFileArtifactPath }}

      - ${{ elseif eq(parameters.projectType, 'cloud') }}:
          - template: ../steps/build-cloud.yml
            parameters:
              tfChildDir: ${{ parameters.tfChildDir }}

      - ${{ elseif eq(parameters.projectType, 'container') }}:
          - template: ../steps/build-container.yml
            parameters:
              # required - force AZ Pipelines validator to throw an error
              ${{ if ne(parameters.dkrECRUrl, '') }}:
                dkrECRUrl: ${{ parameters.dkrECRUrl }}
              dkrFile: ${{ parameters.dkrFile }}
              dkrTag: ${{ parameters.dkrTag }}

      - ${{ if ne(parameters.artifactName, '') }}:
          - template: ../steps/post-build.yml
            parameters:
              artifactName: ${{ parameters.artifactName }}
              artifactDir: ${{ parameters.artifactDir }}
