parameters:
  - name: environmentName
    type: string

  - name: projectType # required. Must be one of: cloud, container, web
    type: string
    values:
      - cloud
      - container-app
      - container-db
      - web

  - name: dotEnvFileArtifactName
    type: string

  - name: dotEnvFileArtifactPath
    type: string

  - name: artifactName # optional, leave blank if you do not need artifacts
    type: string
    default: ""

  ###################################################################
  #                                                                 #
  #   steps/deploy-cloud.yml parameters                             #
  #                                                                 #
  ###################################################################
  # optional if "projectType" = "cloud".
  # Leave empty if root directory, e.g. '.'
  # Terraform execution directory.
  # Name of directory to pass to `-chdir`, e.g. $(Build.SourcesDirectory)/module
  - name: tfChildDir
    type: string
    default: .

  ###################################################################
  #                                                                 #
  #   steps/deploy-container-[app|db].yml parameters                #
  #                                                                 #
  ###################################################################
  - name: dkrECRUrl # required if "projectType" = "container-app" OR "container-db".
    type: string
    default: ""

  - name: dkrTag # optional if "projectType" = "container-app" OR "container-db". Default = latest
    type: string
    default: latest

  ###################################################################
  #                                                                 #
  #   steps/deploy-container-app.yml parameters.                    #
  #                                                                 #
  ###################################################################
  - name: ecsTaskDefFamily # required if "projectType" = "container-app"
    type: string
    default: ""
  - name: ecsRoleArn # required if ecsTaskDefFamily is not empty string.
    type: string
    default: ""
  - name: ecsCpu # required if ecsTaskDefFamily is not empty string.
    type: string
    default: 0
  - name: ecsMemory # required if ecsTaskDefFamily is not empty string.
    type: string
    default: 0
  - name: ecsClusterName # required if ecsTaskDefFamily is not empty string.
    type: string
    default: ""
  - name: ecsSvcName # required if ecsTaskDefFamily is not empty string.
    type: string
    default: ""
  - name: dotEnvFileStorePath # required if ecsTaskDefFamily is not empty string.
    type: string

  - name: port
    type: number
    default: 0

  ###################################################################
  #                                                                 #
  #   steps/deploy-web.yml parameters.                              #
  #                                                                 #
  ###################################################################
  - name: hostBucket # required if "projectType" = "web". AWS S3 Bucket name
    type: string
    default: ""
  - name: cdnId # required if "projectType" = "web"
    type: string
    default: ""
  - name: dist # required if "projectType" = "web". The folder to upload to AWS S3
    type: string
    default: ""

jobs:
  - deployment: deploy
    displayName: deploy ${{ parameters.projectType }} to ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ../steps/artifact-download.yml
              parameters:
                artifactName: ${{ parameters.dotEnvFileArtifactName }}

            - ${{ if ne(parameters.artifactName, '') }}:
                - template: ../steps/artifact-download.yml
                  parameters:
                    artifactName: ${{ parameters.artifactName }}

            - ${{ if eq(parameters.projectType, 'cloud') }}:
                - template: ../steps/deploy-cloud.yml
                  parameters:
                    dotEnvFileArtifactPath: ${{ parameters.dotEnvFileArtifactPath }}
                    tfChildDir: ${{ parameters.tfChildDir }}

            - ${{ if eq(parameters.projectType, 'container-app') }}:
                - template: ../steps/deploy-container-app.yml
                  parameters:
                    # required - force AZ Pipelines validator to throw an error
                    ${{ if ne(parameters.awsRegion, '') }}:
                      awsRegion: ${{ parameters.awsRegion }}
                    ${{ if ne(parameters.dkrECRUrl, '') }}:
                      dkrECRUrl: ${{ parameters.dkrECRUrl }}
                    ${{ if ne(parameters.ecsTaskDefFamily, '') }}:
                      ecsTaskDefFamily: ${{ parameters.ecsTaskDefFamily }}
                      ${{ if ne(parameters.ecsRoleArn, '') }}:
                        ecsRoleArn: ${{ parameters.ecsRoleArn }}
                      ${{ if ne(parameters.ecsClusterName, '') }}:
                        ecsClusterName: ${{ parameters.ecsClusterName }}
                      ${{ if ne(parameters.ecsSvcName, '') }}:
                        ecsSvcName: ${{ parameters.ecsSvcName }}
                      ${{ if ne(parameters.dotEnvFileStorePath, '') }}:
                        dotEnvFileStorePath: ${{ parameters.dotEnvFileStorePath }}

                    dkrTag: ${{ parameters.dkrTag }}
                    ecsCpu: ${{ parameters.ecsCpu }}
                    ecsMemory: ${{ parameters.ecsMemory }}
                    port: ${{ parameters.port }}

            - ${{ elseif eq(parameters.projectType, 'container-db') }}:
                - template: ../steps/deploy-container-db.yml
                  parameters:
                    # required - force AZ Pipelines validator to throw an error
                    ${{ if ne(parameters.dkrECRUrl, '') }}:
                      dkrECRUrl: ${{ parameters.dkrECRUrl }}
                    dkrTag: ${{ parameters.dkrTag }}
                    dotEnvFileArtifactPath: ${{ parameters.dotEnvFileArtifactPath }}

            - ${{ elseif eq(parameters.projectType, 'web') }}:
                - template: ../steps/deploy-web.yml
                  parameters:
                    # required - force AZ Pipelines validator to throw an error
                    ${{ if ne(parameters.hostBucket, '') }}:
                      hostBucket: ${{ parameters.hostBucket }}
                    ${{ if ne(parameters.cdnId, '') }}:
                      cdnId: ${{ parameters.cdnId }}
                    ${{ if ne(parameters.dist, '') }}:
                      dist: ${{ parameters.dist }}

                    invalidateBatchPath: $(Build.SourcesDirectory)/ci/inv-batch.json
