parameters:
  - name: testType # required, must be one of: unit, int
    type: string
    default: unit
    values:
      - unit
      - int

  - name: dotEnvFileArtifactName
    type: string

  - name: dotEnvFilePath
    type: string
    default: ""

  - name: script # required to run tests
    type: string
    default: echo 'Tests not implemented.'

jobs:
  - job: test
    displayName: ${{ parameters.testType }} test
    steps:
      - template: ../steps/artifact-download.yml
        parameters:
          artifactName: ${{ parameters.dotEnvFileArtifactName }}

      - name: Run
        script: |
          source $(echo "${{ parameters.dotEnvFilePath }}")
          ${{ parameters.script }}
