parameters:
  - name: projectName
    type: string

  ###################################################################
  #                                                                 #
  #   stages/load-variables.yml parameters                          #
  #                                                                 #
  ###################################################################
  - name: customScript # Default = empty string. AZ Pipelines support script. If defined, ignores SSM implementation
    type: string
    default: ""

  - name: awsSSMParamPathList # Default = empty string. List of semi-colon seprated strings. AWS SSM Parameter path to pull variables from
    type: string
    default: ""

  - name: awsRegion # Default = empty string. Required if intending to retrieve secrets from AWS SSM Parameter Store.
    type: string
    default: ""

  - name: dotEnvFileDir # Default = '.', Location to store env file on the, e.g. ./path/to/env/file
    type: string
    default: "."

  - name: dotEnvFileName # Default = '.env'. Name for env, e.g. .env
    type: string
    default: ".env"

  - name: dotEnvFileStoreName # Default = empty string. Required if intending to retrieve secrets from AWS SSM Parameter Store. AWS S3 bucket name where env the file will be uploaded to
    type: string
    default: ""

  # Default = empty string.
  # Required if intending to retrieve secrets from AWS SSM Parameter Store.
  # If left empty, env file artifact will not be published
  - name: dotEnvFileArtifactName
    type: string
    default: ""

  ###################################################################
  #                                                                 #
  #   jobs/build.yml parameters                                     #
  #                                                                 #
  ###################################################################
  - name: projectType # required. Must be one of: cloud, container, web
    type: string
    values:
      - cloud
      - container
      - web

  # optional if "projectType" = "cloud".
  # Leave empty if root directory, e.g. '.'
  # Terraform execution directory.
  # Name of directory to pass to `-chdir`, e.g. $(Build.SourcesDirectory)/module
  - name: tfChildDir
    type: string
    default: .

  - name: dkrFile # optional if "projectType" = "container". Default = Dockerfile
    type: string
    default: Dockerfile

  - name: dkrImageRepoName # optional if "projectType" = "container".
    type: string
    default: ""

  # determined and passed as a parameter by pipeline layer
  - name: dkrImageTag # optional if "projectType" = "container". Default = latest
    type: string
    default: latest

  - name: artifactName # optional, leave blank if you do not need artifacts
    type: string
    default: ""

  - name: artifactDir # Default = '.' e.g. $(Build.SourcesDirectory)/dist
    type: string
    default: "."

stages:
  - template: ./load-variables.yml
    parameters:
      projectName: ${{ parameters.projectName }}
      customScript: ${{ parameters.customScript }}
      awsSSMParamPathList: ${{ parameters.awsSSMParamPathList }}
      awsRegion: ${{ parameters.awsRegion }}
      dotEnvFileDir: ${{ parameters.dotEnvFileDir }}
      dotEnvFileName: ${{ parameters.dotEnvFileName }}
      dotEnvFileStoreName: ${{ parameters.dotEnvFileStoreName }}
      dotEnvFileArtifactName: ${{ parameters.dotEnvFileArtifactName }}

  - stage: build
    displayName: build - ${{ parameters.projectName }}
    dependsOn:
      - variables
    jobs:
      - template: ../jobs/build.yml
        parameters:
          projectType: ${{ parameters.projectType }}

          dotEnvFileArtifactName: ${{ parameters.dotEnvFileArtifactName }}
          dotEnvFileArtifactPath: ${{ parameters.dotEnvFileDir }}/${{ parameters.dotEnvFileName }}

          tfChildDir: ${{ parameters.tfChildDir }}

          dkrFile: ${{ parameters.dkrFile }}
          dkrECRUrl: $[stageDependencies.variables.variables.outputs['LoadVariables.IMAGE_REGISTRY_BASE_URL']]

          ${{ if and(ne(parameters.dkrImageRepoName, ''), ne(parameters.dkrImageTag, '')) }}:
            dkrTag: $[stageDependencies.variables.variables.outputs['LoadVariables.IMAGE_REGISTRY_BASE_URL']]/${{ parameters.dkrImageRepoName }}:${{ parameters.dkrImageTag }}

          artifactName: ${{ parameters.artifactName }}
          artifactDir: ${{ parameters.artifactDir }}
