parameters:
  - name: projectName
    type: string

  - name: dotEnvFileArtifactName
    type: string

  ###################################################################
  #                                                                 #
  #   stages/load-variables.yml parameters                          #
  #                                                                 #
  ###################################################################
  - name: customScript # Default = empty string. AZ Pipelines support script. If defined, ignores SSM implementation
    type: string
    default: ""

  - name: awsSSMParamPathList # Default = []. List of strings. AWS SSM Parameter path to pull variables from. If empty, step is disabled.
    type: object
    default: []

  - name: awsRegion # Default = empty string. Required if intending to retrieve secrets from AWS SSM Parameter Store.
    type: string
    default: ""

  - name: dotEnvFileDir # Default = '.', Location to store env file on the, e.g. ./path/to/env/file
    type: string
    default: "."

  - name: dotEnvFileName # Default = '.env'. Name for env, e.g. .env
    type: string
    default: ".env"

  - name: dotEnvFileStoreName # Default = empty string. Required if intending to retrieve secrets from AWS SSM Parameter Store. AWS S3 bucket name where env the file will be uploaded to
    type: string
    default: ""

  ###################################################################
  #                                                                 #
  #   jobs/deploy.yml parameters                                    #
  #                                                                 #
  ###################################################################
  - name: environmentName
    type: string

  - name: projectType # required. Must be one of: cloud, container, web
    type: string
    values:
      - cloud
      - container-app
      - container-db
      - web

  - name: dotEnvFileArtifactPath
    type: string

  - name: artifactName # optional, leave blank if you do not need artifacts
    type: string
    default: ""

  # optional if "projectType" = "cloud".
  # Leave empty if root directory, e.g. '.'
  # Terraform execution directory.
  # Name of directory to pass to `-chdir`, e.g. $(Build.SourcesDirectory)/module
  - name: tfChildDir
    type: string
    default: .

  - name: dkrECRUrl # required if "projectType" = "container-app" OR "container-db".
    type: string
    default: ""

  - name: dkrTag # optional if "projectType" = "container-app" OR "container-db". Default = latest
    type: string
    default: latest

  - name: ecsTaskDefFamily # required if "projectType" = "container-app"
    type: string
    default: ""
  - name: ecsRoleArn # required if ecsTaskDefFamily is not empty string.
    type: string
    default: ""
  - name: ecsCpu # required if ecsTaskDefFamily is not empty string.
    type: string
    default: 0
  - name: ecsMemory # required if ecsTaskDefFamily is not empty string.
    type: string
    default: 0
  - name: ecsClusterName # required if ecsTaskDefFamily is not empty string.
    type: string
    default: ""
  - name: ecsSvcName # required if ecsTaskDefFamily is not empty string.
    type: string
    default: ""
  - name: dotEnvFileStorePath # required if ecsTaskDefFamily is not empty string.
    type: string

  - name: port
    type: number
    default: 0

  - name: hostBucket # required if "projectType" = "web". AWS S3 Bucket name
    type: string
    default: ""
  - name: cdnId # required if "projectType" = "web"
    type: string
    default: ""
  - name: dist # required if "projectType" = "web". The folder to upload to AWS S3
    type: string
    default: ""

stages:
  - template: ./load-variables.yml
    parameters:
      projectName: ${{ parameters.projectName }}
      customScript: ${{ parameters.customScript }}
      awsSSMParamPathList: ${{ parameters.awsSSMParamPathList }}
      awsRegion: ${{ parameters.awsRegion }}
      dotEnvFileDir: ${{ parameters.dotEnvFileDir }}
      dotEnvFileName: ${{ parameters.dotEnvFileName }}
      dotEnvFileStoreName: ${{ parameters.dotEnvFileStoreName }}
      dotEnvFileArtifactName: ${{ parameters.dotEnvFileArtifactName }}

  - stage: deploy
    displayName: deploy - ${{ parameters.projectName }}
    jobs:
      - template: ../jobs/deploy.yml
        parameters:
          environmentName: ${{ parameters.environmentName }}
          projectType: ${{ parameters.projectType }}
          dotEnvFileArtifactName: ${{ parameters.dotEnvFileArtifactName }}
          dotEnvFileArtifactPath: ${{ parameters.dotEnvFileArtifactPath }}
          artifactName: ${{ parameters.artifactName }}
          tfChildDir: ${{ parameters.tfChildDir }}
          dkrECRUrl: ${{ parameters.dkrECRUrl }}
          dkrTag: ${{ parameters.dkrTag }}
          ecsTaskDefFamily: ${{ parameters.ecsTaskDefFamily }}
          ecsRoleArn: ${{ parameters.ecsRoleArn }}
          ecsCpu: ${{ parameters.ecsCpu }}
          ecsMemory: ${{ parameters.ecsMemory }}
          ecsClusterName: ${{ parameters.ecsClusterName }}
          ecsSvcName: ${{ parameters.ecsSvcName }}
          dotEnvFileStorePath: ${{ parameters.dotEnvFileStorePath }}
          port: ${{ parameters.port }}
          hostBucket: ${{ parameters.hostBucket }}
          cdnId: ${{ parameters.cdnId }}
          dist: ${{ parameters.dist }}
