parameters:
  - name: projectName
    type: string

  - name: dotEnvFileArtifactName
    type: string

  - name: dependsOnStage
    type: stringList
    default: []

  ###################################################################
  #                                                                 #
  #   stages/load-variables.yml parameters                          #
  #                                                                 #
  ###################################################################
  - name: customScript # Default = empty string. AZ Pipelines support script. If defined, ignores SSM implementation
    type: string
    default: ""

  - name: awsSSMParamPathList # Default = empty string. List of semi-colon seprated strings. AWS SSM Parameter path to pull variables from
    type: string
    default: ""

  - name: awsRegion # Default = empty string. Required if intending to retrieve secrets from AWS SSM Parameter Store.
    type: string
    default: ""

  - name: dotEnvFileDir # Default = '.', Location to store env file on the, e.g. ./path/to/env/file
    type: string
    default: "."

  - name: dotEnvFileName # Default = '.env'. Name for env, e.g. .env
    type: string
    default: ".env"

  - name: dotEnvFileStoreName # Default = empty string. Required if intending to retrieve secrets from AWS SSM Parameter Store. AWS S3 bucket name where env the file will be uploaded to
    type: string
    default: ""

  ###################################################################
  #                                                                 #
  #   jobs/deploy.yml parameters                                    #
  #                                                                 #
  ###################################################################
  - name: environmentName
    type: string

  - name: projectType # required. Must be one of: cloud, container, web
    type: string
    values:
      - cloud
      - container-app
      - container-db
      - web

  - name: artifactName # optional, leave blank if you do not need artifacts
    type: string
    default: ""

  # optional if "projectType" = "cloud".
  # Leave empty if root directory, e.g. '.'
  # Terraform execution directory.
  # Name of directory to pass to `-chdir`, e.g. $(Build.SourcesDirectory)/module
  - name: tfChildDir
    type: string
    default: .

  - name: dkrImageRepoName # optional if "projectType" = "container".
    type: string
    default: ""

  # determined and passed as a parameter by pipeline layer
  - name: dkrImageTag # optional if "projectType" = "container". Default = latest
    type: string
    default: latest

  - name: dist # required if "projectType" = "web". The folder to upload to AWS S3
    type: string
    default: ""

stages:
  - template: ./load-variables.yml
    parameters:
      projectName: ${{ parameters.projectName }}
      customScript: ${{ parameters.customScript }}
      awsSSMParamPathList: ${{ parameters.awsSSMParamPathList }}
      awsRegion: ${{ parameters.awsRegion }}
      dotEnvFileDir: ${{ parameters.dotEnvFileDir }}
      dotEnvFileName: ${{ parameters.dotEnvFileName }}
      dotEnvFileStoreName: ${{ parameters.dotEnvFileStoreName }}
      dotEnvFileArtifactName: ${{ parameters.dotEnvFileArtifactName }}

  - stage: deploy_${{ parameters.environmentName }}
    displayName: deploy - ${{ parameters.projectName }}
    dependsOn:
      - variables
      - ${{ each stage in parameters.dependsOnStage }}:
          - stage
    jobs:
      - template: ../jobs/deploy.yml
        parameters:
          environmentName: ${{ parameters.environmentName }}
          projectType: ${{ parameters.projectType }}

          dotEnvFileArtifactName: ${{ parameters.dotEnvFileArtifactName }}
          dotEnvFileArtifactPath: ${{ parameters.dotEnvFileDir }}/${{ parameters.dotEnvFileName }}

          artifactName: ${{ parameters.artifactName }}

          tfChildDir: ${{ parameters.tfChildDir }}

          dkrECRUrl: $[stageDependencies.variables.variables.outputs['LoadVariables.IMAGE_REGISTRY_BASE_URL']]
          ${{ if eq(parameters.dkrImageRepoName, '') }}:
            dkrTag: ""
          ${{ else }}:
            dkrTag: $[stageDependencies.variables.variables.outputs['LoadVariables.IMAGE_REGISTRY_BASE_URL']]/${{ parameters.dkrImageRepoName }}:${{ parameters.dkrImageTag }}

          ecsTaskDefFamily: $[stageDependencies.variables.variables.outputs['LoadVariables.TASK_FAMILY']]
          ecsRoleArn: $[stageDependencies.variables.variables.outputs['LoadVariables.TASK_ROLE_ARN']]
          ecsCpu: $[stageDependencies.variables.variables.outputs['LoadVariables.CONTAINER_CPU']]
          ecsMemory: $[stageDependencies.variables.variables.outputs['LoadVariables.CONTAINER_MEMORY_RESERVATION']]
          ecsClusterName: $[stageDependencies.variables.variables.outputs['LoadVariables.CLUSTER_NAME']]
          ecsSvcName: $[stageDependencies.variables.variables.outputs['LoadVariables.SERVICE_NAME']]
          port: $[stageDependencies.variables.variables.outputs['LoadVariables.CONTAINER_PORT']]
          dotEnvFileStorePath: ${{ parameters.dotEnvFileStoreName }}/${{ parameters.dotEnvFileDir }}/${{ parameters.dotEnvFileName }}

          hostBucket: $[stageDependencies.variables.variables.outputs['LoadVariables.S3_HOST_BUCKET_URL']]
          cdnId: $[stageDependencies.variables.variables.outputs['LoadVariables.CDN_ID']]
          dist: ${{ parameters.dist }}
