parameters:
  - name: projectName
    type: string

  - name: dotEnvFileArtifactName
    type: string

  - name: dependsOnStage
    type: stringList
    default: []

  ###################################################################
  #                                                                 #
  #   stages/load-variables.yml parameters                          #
  #                                                                 #
  ###################################################################
  - name: customScript # Default = empty string. AZ Pipelines support script. If defined, ignores SSM implementation
    type: string
    default: ""

  - name: awsSSMParamPathList # Default = empty string. List of semi-colon seprated strings. AWS SSM Parameter path to pull variables from
    type: string
    default: ""

  - name: awsRegion # Default = empty string. Required if intending to retrieve secrets from AWS SSM Parameter Store.
    type: string
    default: ""

  - name: dotEnvFileDir # Default = '.', Location to store env file on the, e.g. ./path/to/env/file
    type: string
    default: "."

  - name: dotEnvFileName # Default = '.env'. Name for env, e.g. .env
    type: string
    default: ".env"

  - name: dotEnvFileStoreName # Default = empty string. Required if intending to retrieve secrets from AWS SSM Parameter Store. AWS S3 bucket name where env the file will be uploaded to
    type: string
    default: ""

  ###################################################################
  #                                                                 #
  #   jobs/test.yml parameters                                      #
  #                                                                 #
  ###################################################################
  - name: testType # required, must be one of: unit, int
    type: string
    default: unit
    values:
      - unit
      - int

  - name: environmentName # required, must be one of: unit, int
    type: string
    default: local
    values:
      - local
      - qa

  - name: script # required to run tests
    type: string
    default: echo 'Tests not implemented.'

stages:
  - template: ./load-variables.yml
    parameters:
      projectName: ${{ parameters.projectName }}
      customScript: ${{ parameters.customScript }}
      awsSSMParamPathList: ${{ parameters.awsSSMParamPathList }}
      awsRegion: ${{ parameters.awsRegion }}
      dotEnvFileDir: ${{ parameters.dotEnvFileDir }}
      dotEnvFileName: ${{ parameters.dotEnvFileName }}
      dotEnvFileStoreName: ${{ parameters.dotEnvFileStoreName }}
      dotEnvFileArtifactName: ${{ parameters.dotEnvFileArtifactName }}

  - stage: test_${{ parameters.environmentName }}_${{ parameters.testType }}
    displayName: test - ${{ parameters.projectName }}
    dependsOn:
      - variables
      - ${{ each stage in parameters.dependsOnStage }}:
          - stage
    jobs:
      - template: ../jobs/test.yml
        parameters:
          testType: ${{ parameters.testType }}
          environmentName: ${{ parameters.environmentName }}
          dotEnvFileArtifactName: ${{ parameters.dotEnvFileArtifactName }}
          dotEnvFilePath: ${{ parameters.dotEnvFileDir }}/${{ parameters.dotEnvFileName }}
          script: ${{ parameters.script }}
